<?php

namespace Database\Seeders;

use App\Models\Parametro;
use Illuminate\Database\Seeder;

class ParametroSeeder extends Seeder
{
    public function run(): void
    {
        $parametros = [
            // ===== PARÁMETROS AMBIENTALES =====
            // -- AIRE: Partículas --
            [
                'nombre' => 'PTS',
                'nombre_completo' => 'Partículas Totales Suspendidas',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas Totales Suspendidas - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM10',
                'nombre_completo' => 'Partículas menores a 10 micras',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 10 micras - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM4',
                'nombre_completo' => 'Partículas menores a 4 micras',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 4 micras - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM2.5',
                'nombre_completo' => 'Partículas menores a 2.5 micras',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 2.5 micras - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM1',
                'nombre_completo' => 'Partículas menores a 1 micra',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 1 micra - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            // -- RUIDO --
            [
                'nombre' => 'RUIDO',
                'nombre_completo' => 'Medición de Ruido Ambiental',
                'metodo' => 'SONÓMETRO',
                'descripcion' => 'Medición de Ruido Ambiental - método SONÓMETRO',
                'tipo_medicion' => 'Ambiental',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'RUIDO',
                'unidad_default' => 'dB(A)',
            ],
            [
                'nombre' => 'RUIDO',
                'nombre_completo' => 'Medición de Ruido Industrial',
                'metodo' => 'SONÓMETRO',
                'descripcion' => 'Medición de Ruido Industrial - método SONÓMETRO',
                'tipo_medicion' => 'Industrial',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'RUIDO',
                'unidad_default' => 'dB(A)',
            ],
            // -- GASES --
            [
                'nombre' => 'NO',
                'nombre_completo' => 'Monóxido de Nitrógeno',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Monóxido de Nitrógeno - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => 'ppm',
            ],
            [
                'nombre' => 'CO',
                'nombre_completo' => 'Monóxido de Carbono',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Monóxido de Carbono - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => 'ppm',
            ],
            [
                'nombre' => 'O2',
                'nombre_completo' => 'Oxígeno',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Oxígeno - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => '%',
            ],
            [
                'nombre' => 'H2S',
                'nombre_completo' => 'Sulfuro de Hidrógeno',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Sulfuro de Hidrógeno - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => 'ppm',
            ],
            [
                'nombre' => '%LEL',
                'nombre_completo' => 'Límite Inferior de Explosividad',
                'metodo' => 'Sensor Catalítico/Infrarrojo',
                'descripcion' => 'Límite Inferior de Explosividad - método Sensor Catalítico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => '%',
            ],

            // Parámetros de AGUA
            // POTENCIOMETRO
            [
                'nombre' => 'pH',
                // S'metodo' => 'POE-1-01 Potenciometría',
                'metodo' => 'APHA-AWWA-WPCF 4500-H+, B Método electrométrico',
                'codigo_poe' => 'POE 1-01',
                'limite_cuantificacion' => '4,00 a 10,00',
                'unidad' => 'unid pH',
                'precio_unitario' => 20.00, // el costo real es 20 bs
                'matriz' => 'AGUA',
                'tecnica' => 'POTENCIOMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Conductividad',
                // 'metodo' => 'POE-1-02 Potenciometría',
                'metodo' => 'APHA-AWWA-WPCF.2510 B Método de laboratorio',
                'codigo_poe' => 'POE 1-02',
                'limite_cuantificacion' => '14,9 a 1413',
                'unidad' => ' µS/cm',
                'precio_unitario' => 150.00, // precio real 20 bs
                'matriz' => 'AGUA',
                'tecnica' => 'POTENCIOMETRIA',
                'tipo' => 'AGUA',
            ],
            // ABSORCION ATOMICA - Llama normal
            [
                'nombre' => 'Plomo - Pb',
                'metodo' => 'JISK 0102 54.1',
                'codigo_poe' => 'POE 1-12',
                'limite_cuantificacion' => '0,09',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00, // precio real 20 bs
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA - Llama normal',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cadmio - Cd',
                'metodo' => 'JISK 0102 53.1',
                'codigo_poe' => 'POE 1-13',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00, // precio real 20 bs
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA - Llama normal',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Niquel - Ni',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE 1-14',
                'limite_cuantificacion' => '0,025',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA - Llama normal',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Plata - Ag',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE 1-16',
                'limite_cuantificacion' => '0,10',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA - Llama normal',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Potasio - K',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-20',
                'limite_cuantificacion' => '0,30',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Litio - Li',
                'metodo' => 'APHA 3500-Li-B',
                'codigo_poe' => 'POE-1-21',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 50,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],

            [
                'nombre' => 'Manganeso - Mn',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-125',
                'limite_cuantificacion' => '0,010',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],

            [
                'nombre' => 'Zinc - Zn',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-126',
                'limite_cuantificacion' => '0,028',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sodio - Na',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-127',
                'limite_cuantificacion' => '0,58',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Calcio - Ca',
                'metodo' => 'ASTM D511-14 TEST METHOD B',
                'codigo_poe' => 'POE-1-04',
                'limite_cuantificacion' => '1,00 mg/l a 1500 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Magnesio - Mg',
                'metodo' => 'ASTM D511 - TEST METHOD B, con modificaciones validadas',
                'codigo_poe' => 'POE-1-05',
                'limite_cuantificacion' => '0,25 mg/l a 350 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cobre - Cu',
                'metodo' => 'Basado en ASTM D 1688',
                'codigo_poe' => 'POE-1-06',
                'limite_cuantificacion' => '0,05 mg/l a 4,41 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Hierro - Fe',
                'metodo' => 'Basado en ASTM D 1068',
                'codigo_poe' => 'POE-1-07',
                'limite_cuantificacion' => '0,100 mg/l a 2,00 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            // FOTOMETRIA
            [
                'nombre' => 'Cloro Residual',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-58',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 45,
                'matriz' => 'AGUA',
                'tecnica' => 'FOTOMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cloro Total',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-59',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 45,
                'matriz' => 'AGUA',
                'tecnica' => 'FOTOMETRIA',
                'tipo' => 'AGUA',
            ],
            // UV-VISIBLE
            [
                'nombre' => 'Sulfatos - SO4',   // MEJORAR NOMBRE
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-60',
                'limite_cuantificacion' => '0,5',
                'unidad' => 'mg/l',
                'precio_unitario' => 50,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Fosfatos - PO4 ',   // MEJORAR NOMBRE
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-61',
                'limite_cuantificacion' => '0,025',
                'unidad' => 'mg/l',
                'precio_unitario' => 60,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Nitritos - NO2',   // MEJORAR NOMBRE
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-62',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 60,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Nitratos - NO3',   // MEJORAR NOMBRE
                'metodo' => 'JISK',
                // 'codigo_poe' => 'POE-1-63',
                // 'limite_cuantificacion' => '0,1',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 60,
                // 'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Boro - B',   // MEJORAR NOMBRE
                'metodo' => 'APHA 4500B',
                'codigo_poe' => 'POE-1-65',
                'limite_cuantificacion' => '0,05',
                'unidad' => 'mg/l',
                'precio_unitario' => 60,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cromo hexavalente.-Cr+6',   // MEJORAR NOMBRE
                'metodo' => 'JISK 0102 65.1.1.2',
                // 'codigo_poe' => 'POE-1-66',
                // 'limite_cuantificacion' => '0,01',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 60,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cromo trivalente - Cr+3',   // MEJORAR NOMBRE
                'metodo' => 'JISK 0102 65.1.1.2',
                // 'codigo_poe' => 'POE-1-67',
                // 'limite_cuantificacion' => '0,01',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 60,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sulfuros - S=',   // MEJORAR NOMBRE
                'metodo' => 'JISK',
                // 'codigo_poe' => 'POE-1-72',
                // 'limite_cuantificacion' => '0,0103',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 60,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Fósforo Total - P T',
                'metodo' => 'JISK',
                // 'codigo_poe' => 'POE-1-75',
                // 'limite_cuantificacion' => '0,1',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 60,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cromo total',
                'metodo' => 'JISK 0102 65.1.1.2',
                // 'codigo_poe' => 'POE-1-143',
                // 'limite_cuantificacion' => '0,01',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 70,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            // IONOMETRIA
            [
                'nombre' => 'Cloruros - Cl-',
                'metodo' => 'JISK',
                // 'codigo_poe' => 'POE-1-76',
                // 'limite_cuantificacion' => '0,5',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 50,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Amonio - NH4',
                'metodo' => 'JISK',
                // 'codigo_poe' => 'POE-1-77',
                // 'limite_cuantificacion' => '0,04',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 50,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cianuro libre',
                'metodo' => 'JISK 0102 38.4',
                // 'codigo_poe' => 'POE-1-78',
                // 'limite_cuantificacion' => '0,03',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 50,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Fluoruros - F-',
                'metodo' => 'JISK',
                // 'codigo_poe' => ' POE-1-79',
                // 'limite_cuantificacion' => '0,01',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 50,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            // VOLUMETRIA
            [
                'nombre' => 'Dureza',
                'metodo' => 'APHA-AWWA-WPCF 2340 C, Método titrimetrico',
                // 'codigo_poe' => ' POE-1-03',
                // 'limite_cuantificacion' => '15,19 a 2300',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 40,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'DBO',
                'metodo' => 'APHA 5210-B',
                // 'codigo_poe' => ' POE-1-80',
                // 'limite_cuantificacion' => '2',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 95,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'DQO',
                'metodo' => 'APHA 5220-B',
                // 'codigo_poe' => 'POE-1-81',
                // 'limite_cuantificacion' => '2',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 95,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'OD',
                'metodo' => 'JISK 0102 32.1',
                // 'codigo_poe' => 'POE-1-82',
                // 'limite_cuantificacion' => '2',
                // 'unidad' => 'mg/l',
                'precio_unitario' => 50,
                // 'matriz' => 'AGUA',
                'tecnica' => 'ABSORCIÓN ATÓMICA',
                'tipo' => 'AGUA',
            ],

            [
                'nombre' => 'Color',
                'metodo' => 'POE-1-71 Otros',
                'precio_unitario' => 180.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Turbidez',
                'metodo' => 'POE-1-97 Nefelometria',
                'precio_unitario' => 160.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Solidos Suspendidos T.',
                'metodo' => 'POE-1-91 Gravimetría',
                'precio_unitario' => 240.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Aceites y Grasas',
                'metodo' => 'POE-1-96 Gravimetria',
                'precio_unitario' => 280.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'DBO5',
                'metodo' => 'POE-1-80 Volumetria',
                'precio_unitario' => 300.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Coliformes Fecales',
                'metodo' => 'POE-1-103 Filtro de membrana',
                'precio_unitario' => 260.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'E. Coli',
                'metodo' => 'POE-1-105 Filtro de membrana',
                'precio_unitario' => 270.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cianuro Libre',
                'metodo' => 'POE-1-78 Ionometria',
                'precio_unitario' => 350.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cloro Residual',
                'metodo' => 'POE-1-58 Fotometria',
                'precio_unitario' => 190.00,
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sulfatos',
                'metodo' => 'POE-1-60 UV Visible',
                'precio_unitario' => 230.00,
                'tipo' => 'AGUA',
            ],
        ];

        foreach ($parametros as $parametro) {
            $unique = ['nombre' => $parametro['nombre']];
            if (! empty($parametro['tipo_medicion'])) {
                $unique['tipo_medicion'] = $parametro['tipo_medicion'];
            }
            Parametro::updateOrCreate($unique, $parametro);
        }

        $this->command->info('✅ Parámetros verificados/creados correctamente');
    }
}
