<?php

namespace Database\Seeders;

use App\Models\Parametro;
use Illuminate\Database\Seeder;

class ParametroSeeder extends Seeder
{
    public function run(): void
    {
        $parametros = [
            // ===== PARÁMETROS AMBIENTALES =====
            // -- AIRE: Partículas --
            [
                'nombre' => 'PTS',
                'nombre_completo' => 'Partículas Totales Suspendidas',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas Totales Suspendidas - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM10',
                'nombre_completo' => 'Partículas menores a 10 micras',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 10 micras - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM4',
                'nombre_completo' => 'Partículas menores a 4 micras',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 4 micras - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM2.5',
                'nombre_completo' => 'Partículas menores a 2.5 micras',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 2.5 micras - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            [
                'nombre' => 'PM1',
                'nombre_completo' => 'Partículas menores a 1 micra',
                'metodo' => 'TAS (Tactical Air Sampler) USA',
                'descripcion' => 'Partículas menores a 1 micra - método TAS USA',
                'precio_unitario' => 250.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'AIRE',
                'unidad_default' => 'µg/m³',
            ],
            // -- RUIDO --
            [
                'nombre' => 'RUIDO',
                'nombre_completo' => 'Medición de Ruido Ambiental',
                'metodo' => 'SONÓMETRO',
                'descripcion' => 'Medición de Ruido Ambiental - método SONÓMETRO',
                'tipo_medicion' => 'Ambiental',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'RUIDO',
                'unidad_default' => 'dB(A)',
            ],
            [
                'nombre' => 'RUIDO',
                'nombre_completo' => 'Medición de Ruido Industrial',
                'metodo' => 'SONÓMETRO',
                'descripcion' => 'Medición de Ruido Industrial - método SONÓMETRO',
                'tipo_medicion' => 'Industrial',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'RUIDO',
                'unidad_default' => 'dB(A)',
            ],
            // -- GASES --
            [
                'nombre' => 'NO',
                'nombre_completo' => 'Monóxido de Nitrógeno',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Monóxido de Nitrógeno - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => 'ppm',
            ],
            [
                'nombre' => 'CO',
                'nombre_completo' => 'Monóxido de Carbono',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Monóxido de Carbono - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => 'ppm',
            ],
            [
                'nombre' => 'O₂',
                'nombre_completo' => 'Oxígeno',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Oxígeno - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => '%',
            ],
            [
                'nombre' => 'H₂S',
                'nombre_completo' => 'Sulfuro de Hidrógeno',
                'metodo' => 'Sensor Electroquímico/Analizador de Gases',
                'descripcion' => 'Sulfuro de Hidrógeno - método Sensor Electroquímico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => 'ppm',
            ],
            [
                'nombre' => '%LEL',
                'nombre_completo' => 'Límite Inferior de Explosividad',
                'metodo' => 'Sensor Catalítico/Infrarrojo',
                'descripcion' => 'Límite Inferior de Explosividad - método Sensor Catalítico',
                'precio_unitario' => 90.00,
                'tipo' => 'AMBIENTAL',
                'categoria' => 'GASES',
                'unidad_default' => '%',
            ],

            // ============================================================
            // MATRIZ: AGUA
            // ============================================================

            // ---------- POTENCIOMETRIA ----------
            [
                'nombre' => 'pH',
                'metodo' => 'APHA-AWWA-WPCF 4500-H+, B Método electrométrico',
                'codigo_poe' => 'POE 1-014',
                'limite_cuantificacion' => '4,00 a 10,00',
                'unidad' => 'unid pH',
                'precio_unitario' => 20.00,
                'matriz' => 'AGUA',
                'tecnica' => 'POTENCIOMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Conductividad',
                'metodo' => 'APHA-AWWA-WPCF. 2510 B Método de laboratorio',
                'codigo_poe' => 'POE 1-021',
                'limite_cuantificacion' => '4,9 a 1413',
                'unidad' => 'μS/cm',
                'precio_unitario' => 20.00,
                'matriz' => 'AGUA',
                'tecnica' => 'POTENCIOMETRIA',
                'tipo' => 'AGUA',
            ],

            // ---------- ABSORCIÓN ATÓMICA ----------
            [
                'nombre' => 'Plomo - Pb',
                'metodo' => 'JISK 0102 54.1',
                'codigo_poe' => 'POE-1-120',
                'limite_cuantificacion' => '0,09',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cadmio - Cd',
                'metodo' => 'JISK 0102 53.1',
                'codigo_poe' => 'POE-1-130',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Niquel - Ni',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-140',
                'limite_cuantificacion' => '0,025',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Plata - Ag',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-160',
                'limite_cuantificacion' => '0,10',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Potasio - K',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-200',
                'limite_cuantificacion' => '0,30',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Litio - Li',
                'metodo' => 'APHA 3500-Li-B',
                'codigo_poe' => 'POE-1-210',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Manganese - Mn',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-125',
                'limite_cuantificacion' => '0,010',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Zinc - Zn',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-126',
                'limite_cuantificacion' => '0,028',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sodio - Na',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-127',
                'limite_cuantificacion' => '0,58',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Calcio - Ca',
                'metodo' => 'ASTM D511-14 TEST METHOD B',
                'codigo_poe' => 'POE-1-041',
                'limite_cuantificacion' => '1,00 mg/l a 1500 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Magnesio - Mg',
                'metodo' => 'ASTM D 511 - TEST METHOD B, con modificaciones validadas',
                'codigo_poe' => 'POE-1-050',
                'limite_cuantificacion' => '0,25 mg/l a 350 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cobre - Cu',
                'metodo' => 'Basado en ASTM D 1688',
                'codigo_poe' => 'POE-1-060',
                'limite_cuantificacion' => '0,05 mg/l a 4,41 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Hierro - Fe',
                'metodo' => 'Basado en ASTM D1068',
                'codigo_poe' => 'POE-1-070',
                'limite_cuantificacion' => '0,100 mg/l a 2,00 mg/l',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'ABSORCION ATOMICA',
                'tipo' => 'AGUA',
            ],

            // ---------- FOTOMETRIA ----------
            [
                'nombre' => 'Cloro Residual',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-580',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 45.00,
                'matriz' => 'AGUA',
                'tecnica' => 'FOTOMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cloro Total',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-590',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 45.00,
                'matriz' => 'AGUA',
                'tecnica' => 'FOTOMETRIA',
                'tipo' => 'AGUA',
            ],

            // ---------- UV - VISIBLE ----------
            [
                'nombre' => 'Sulfatos - SO4',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-600',
                'limite_cuantificacion' => '0,5',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Fosfatos - PO4',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-610',
                'limite_cuantificacion' => '0,025',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Nitritos - NO2',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-620',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Nitratos - NO3',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-630',
                'limite_cuantificacion' => '0,1',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Boro - B',
                'metodo' => 'APHA 4500B',
                'codigo_poe' => 'POE-1-650',
                'limite_cuantificacion' => '0,05',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cromo hexavalente - Cr+6',
                'metodo' => 'JISK 0102 65.1.1.2',
                'codigo_poe' => 'POE-1-660',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cromo trivalente - Cr+3',
                'metodo' => 'JISK 0102 65.1.1.2',
                'codigo_poe' => 'POE-1-670',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sulfuros - S-',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-720',
                'limite_cuantificacion' => '0,0103',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Fósforo Total - P T',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-750',
                'limite_cuantificacion' => '0,1',
                'unidad' => 'mg/l',
                'precio_unitario' => 60.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cromo total',
                'metodo' => 'JISK 0102 65.1.1.2',
                'codigo_poe' => 'POE-1-143',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 70.00,
                'matriz' => 'AGUA',
                'tecnica' => 'UV-VISIBLE',
                'tipo' => 'AGUA',
            ],

            // ---------- IONOMETRIA ----------
            [
                'nombre' => 'Cloruros - Cl-',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-760',
                'limite_cuantificacion' => '0,5',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'IONOMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Amonio - NH4',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-770',
                'limite_cuantificacion' => '0,04',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'IONOMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Cianuro libre',
                'metodo' => 'JISK 0102 38.4',
                'codigo_poe' => 'POE-1-780',
                'limite_cuantificacion' => '0,03',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'IONOMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Fluoruros - F-',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-790',
                'limite_cuantificacion' => '0,01',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'IONOMETRIA',
                'tipo' => 'AGUA',
            ],

            // ---------- VOLUMETRÍA ----------
            [
                'nombre' => 'Dureza',
                'metodo' => 'APHA-AWWA-WPCF 2340 C, Método titrimétrico',
                'codigo_poe' => 'POE-1-031',
                'limite_cuantificacion' => '15,19 a 2300',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'DBO',
                'metodo' => 'APHA 5210-B',
                'codigo_poe' => 'POE-1-802',
                'limite_cuantificacion' => '2',
                'unidad' => 'mg/l',
                'precio_unitario' => 95.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'DQO',
                'metodo' => 'APHA 5220-B',
                'codigo_poe' => 'POE-1-811',
                'limite_cuantificacion' => '2',
                'unidad' => 'mg/l',
                'precio_unitario' => 95.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'OD',
                'metodo' => 'JISK 0102 32.1',
                'codigo_poe' => 'POE-1-822',
                'limite_cuantificacion' => '2',
                'unidad' => 'mg/l',
                'precio_unitario' => 50.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Acidez Total',
                'metodo' => 'JISK 0102 15',
                'codigo_poe' => 'POE-1-840',
                'limite_cuantificacion' => '0,1',
                'unidad' => 'mg/l',
                'precio_unitario' => 35.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Alcalinidad Total',
                'metodo' => 'JISK 0102 16',
                'codigo_poe' => 'POE-1-850',
                'limite_cuantificacion' => '0,1',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Carbonatos - CO3',
                'metodo' => 'JISK 0102 16',
                'codigo_poe' => 'POE-1-860',
                'limite_cuantificacion' => '0,1',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Bicarbonatos - HCO3',
                'metodo' => 'APHA 2540',
                'codigo_poe' => 'POE-1-870',
                'limite_cuantificacion' => '0,1',
                'unidad' => 'mg/l',
                'precio_unitario' => 40.00,
                'matriz' => 'AGUA',
                'tecnica' => 'VOLUMETRIA',
                'tipo' => 'AGUA',
            ],

            // ---------- GRAVIMETRÍA ----------
            [
                'nombre' => 'Sólidos Suspendidos',
                'metodo' => 'JISK 0102 14.1',
                'codigo_poe' => 'POE-1-912',
                'limite_cuantificacion' => '2,0',
                'unidad' => 'mg/l',
                'precio_unitario' => 30.00,
                'matriz' => 'AGUA',
                'tecnica' => 'GRAVIMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sólidos Totales',
                'metodo' => 'JISK 0102 14.2',
                'codigo_poe' => 'POE-1-922',
                'limite_cuantificacion' => '2,0',
                'unidad' => 'mg/l',
                'precio_unitario' => 30.00,
                'matriz' => 'AGUA',
                'tecnica' => 'GRAVIMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sólidos Disueltos',
                'metodo' => 'JISK 0102 14.3',
                'codigo_poe' => 'POE-1-932',
                'limite_cuantificacion' => '2,0',
                'unidad' => 'mg/l',
                'precio_unitario' => 30.00,
                'matriz' => 'AGUA',
                'tecnica' => 'GRAVIMETRIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Aceites y grasas',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-962',
                'limite_cuantificacion' => '2,0',
                'unidad' => 'mg/l',
                'precio_unitario' => 100.00,
                'matriz' => 'AGUA',
                'tecnica' => 'GRAVIMETRIA',
                'tipo' => 'AGUA',
            ],

            // ---------- NEFELOMÉTRICO ----------
            [
                'nombre' => 'Turbidez',
                'metodo' => 'APHA 2130B',
                'codigo_poe' => 'POE-1-970',
                'limite_cuantificacion' => '0,02',
                'unidad' => 'NTU',
                'precio_unitario' => 15.00,
                'matriz' => 'AGUA',
                'tecnica' => 'NEFELOMÉTRICO',
                'tipo' => 'AGUA',
            ],

            // ---------- BACTEREOLOGÍA ----------
            [
                'nombre' => 'Coliformes fecales',
                'metodo' => 'Filtro de membrana',
                'codigo_poe' => 'POE-1-103',
                'limite_cuantificacion' => '---',
                'unidad' => 'UFC/100ml',
                'precio_unitario' => 85.00,
                'matriz' => 'AGUA',
                'tecnica' => 'BACTEREOLOGIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Coliformes totales',
                'metodo' => 'Filtro de membrana',
                'codigo_poe' => 'POE-1-104',
                'limite_cuantificacion' => '---',
                'unidad' => 'UFC/100ml',
                'precio_unitario' => 85.00,
                'matriz' => 'AGUA',
                'tecnica' => 'BACTEREOLOGIA',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Escherichia coli',
                'metodo' => 'Filtro de membrana',
                'codigo_poe' => 'POE-1-105',
                'limite_cuantificacion' => '---',
                'unidad' => 'UFC/100ml',
                'precio_unitario' => 85.00,
                'matriz' => 'AGUA',
                'tecnica' => 'BACTEREOLOGIA',
                'tipo' => 'AGUA',
            ],

            // ---------- OTROS ----------
            [
                'nombre' => 'Temperatura',
                'metodo' => 'APHA-AWWA-WPCF',
                'codigo_poe' => 'POE-1-119',
                'limite_cuantificacion' => '---',
                'unidad' => '°C',
                'precio_unitario' => 15.00,
                'matriz' => 'AGUA',
                'tecnica' => 'OTROS',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Densidad',
                'metodo' => 'JISK',
                'codigo_poe' => 'POE-1-120',
                'limite_cuantificacion' => '---',
                'unidad' => 'g/cm3',
                'precio_unitario' => 15.00,
                'matriz' => 'AGUA',
                'tecnica' => 'OTROS',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Olor',
                'metodo' => 'APHA-AWWA-WPCF',
                'codigo_poe' => 'POE-1-123',
                'limite_cuantificacion' => '---',
                'unidad' => 'NUO',
                'precio_unitario' => 20.00,
                'matriz' => 'AGUA',
                'tecnica' => 'OTROS',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Sabor',
                'metodo' => 'APHA-AWWA-WPCF',
                'codigo_poe' => 'POE-1-124',
                'limite_cuantificacion' => '---',
                'unidad' => 'NUS',
                'precio_unitario' => 20.00,
                'matriz' => 'AGUA',
                'tecnica' => 'OTROS',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Color',
                'metodo' => 'APHA 2120 B',
                'codigo_poe' => 'POE-1-711',
                'limite_cuantificacion' => '---',
                'unidad' => 'UCV',
                'precio_unitario' => 20.00,
                'matriz' => 'AGUA',
                'tecnica' => 'OTROS',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'Salinidad',
                'metodo' => 'APHA 4500',
                'codigo_poe' => 'POE-1-980',
                'limite_cuantificacion' => '0,1',
                'unidad' => 'g/l',
                'precio_unitario' => 20.00,
                'matriz' => 'AGUA',
                'tecnica' => 'OTROS',
                'tipo' => 'AGUA',
            ],
            [
                'nombre' => 'RAS',
                'metodo' => '---',
                'codigo_poe' => 'POE-1-105',
                'limite_cuantificacion' => '---',
                'unidad' => '---',
                'precio_unitario' => 30.00,
                'matriz' => 'AGUA',
                'tecnica' => 'OTROS',
                'tipo' => 'AGUA',
            ],
        ];

        foreach ($parametros as $parametro) {
            $unique = ['nombre' => $parametro['nombre']];
            if (! empty($parametro['tipo_medicion'])) {
                $unique['tipo_medicion'] = $parametro['tipo_medicion'];
            }
            Parametro::updateOrCreate($unique, $parametro);
        }

        $this->command->info('✅ Parámetros verificados/creados correctamente');
    }
}
